apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-qa
spec:
  template:
    metadata:
      name: pod-java-qa
      labels:
        app: lable-pod-java-qa
    spec:
      containers:
        - name: container-java-qa
          image: alexandreponte/validadorcpfjavagoku
          ports:
            - containerPort: 8081
  replicas: 1
  selector:
    matchLabels:
      app: lable-pod-java-qa