apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-prod
spec:
  template:
    metadata:
      name: pod-java-prod
      labels:
        app: lable-pod-java-prod
    spec:
      containers:
        - name: container-java-prod
          image: alexandreponte/validadorcpfjavagoku
          ports:
            - containerPort: 8081
  replicas: 1
  selector:
    matchLabels:
      app: lable-pod-java-prod
